# docker/development/docker-compose.yml
services:
  app:
    container_name: perfectorder-app
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    image: perfectorder:dev-1.00
    ports:
      - "8001:80"
    environment:
      - DB_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ../..:/var/www/perfectorder
      - ./storage:/var/www/perfectorder/storage

  mysql:
    container_name: perfectorder-mysql
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - perfectorder_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  perfectorder_mysql_data:
