services:
    app:
        container_name: perfectorder-app
        build:
            context: .
            dockerfile: Dockerfile
        image: perfectorder:1.00
        ports:
            - "8001:80"
        environment:
            - DB_HOST=mysql
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - .:/var/www/perfectorder
            - ./storage:/var/www/perfectorder/storage  # Persist storage

    mysql:
        container_name: perfectorder-mysql
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - "3307:3306"  # Expose MySQL on host port 3307
        volumes:
            - perfectorder_mysql_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

volumes:
    perfectorder_mysql_data:
